### ISSUE TITLE
Why don't StackScript?

### ISSUE THREAD

**Issue by rodber** [mherrmann/sentry-self-hosted#3]
If I understand you correctly, you created this repo because you want to run Sentry on Linode and make it accesible for everybody.

Your goal is great, but I think that you can chop these 30 min required to make it work. Linode offers StackScripts which ease all the steps you described in README.

For example, this is an old sentry StackScript:
https://www.linode.com/stackscripts/view/12487

It will be awesome if you could use that tool. Besides, your script will be directly available for any Linode user.

Keep up the good work,
Rodolfo.

**Comment by mherrmann** [comment]
Thank you for the suggestion. I don't feel it's worth the hassle of introducing the dependency on StackScript, either for me as the maintainer, or for users of this repository. scp'ing `install.sh` onto a server is easy enough. Also, the current version of the script requires you to change (in the script) some values. I don't know how to do this with a StackScript. Finally, the current "script only" approach lets you also use it on hosting providers other than Linode.
